# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "/digital-playbook-guide-numerique" # the subpath of your site, e.g. /blog
url: "http://canada-ca.github.io" # the base hostname & protocol for your site
twitter_username: canada-ca
github_username:  canada-ca
wet_cdts_hosturl: "https://www.canada.ca/etc/designs/canada/cdts/gcweb"
wet_cdts_version: "v4_0_27"
exclude: ['CONTRIBUTING.md', 'LICENSE.md', 'README.md', 'node_modules/', '\.*', "Gemfile", "*.rb", "link-check.js", "package*.json"]
markdown: kramdown
kramdown:
  parse_block_html: true
  toc_levels: "2..2"

# Collections settings (for the alternate views)
collections_dir: views
collections:
  single_page:
    output: true
    permalink: /:path

# Translations
email: zzOneGC@tbs-sct.gc.ca
description:
  en: The Government of Canada Digital Playbook provides practical and measurable guidance to assist individual projects with becoming more agile, open and user-focused by applying the Digital Standards.
  fr: Le guide numérique du gouvernement du Canada fournit des conseils pratiques et des projets pour aider les projets individuels à devenir plus agiles, ouverts et axés sur l'utilisateur en appliquant les normes numériques.
creator:
  en: Government of Canada, Treasury Board of Canada Secretariat, Chief Information Officer Branch, OneGC Program Office
  fr: Gouvernement du Canada, Secrétariat du Conseil du Trésor du Canada, Direction du dirigeant principal de l’information, Bureau du programme unGC
subject:
  en: Digital Playbook, Government of Canada, services
  fr: Guide numérique, Gouvernement du Canada, services
playbookData:
  en: playbook
  fr: guide
overviewFile:
  en: overview
  fr: apercu
standardFile:
  -
    en:  1-design-with-users
    fr:  1-concevoir-avec-utilisateurs
  -
    en:  2-build-in-accessibility-from-start
    fr:  2-integrer-accessibilite-des-depart
  -
    en:  3-collaborate-widely
    fr:  3-collaborer-largement
  -
    en:  4-empower-staff-deliver-better-services
    fr:  4-permettre-personnel-offrir-meilleurs-services
  -
    en:  5-work-in-open-by-default
    fr:  5-travailler-ouvertement-par-defaut
  -
    en:  6-use-open-standards-solutions
    fr:  6-utiliser-normes-solutions-ouvertes
  -
    en:  7-iterate-improve-frequently
    fr:  7-effectuer-iterations-ameliorations-constamment
  -
    en:  8-design-ethical-services
    fr:  8-concevoir-services-ethiques
  -
    en:  9-address-security-privacy-risks
    fr:  9-gerer-risques-matiere-securite-protection-renseignements-personnels
  -
    en:  10-be-good-data-stewards
    fr:  10-etre-bons-utilisateurs-donnees
RenderedFileExtension: ".html"

# Common strings and tags for the datasets
common:
  introduction:
    tags: ["dpgn-section-overview"]
  standards:
      title:
        en: "Digital Standards"
        fr: "Normes numériques"
      tags: ["dpgn-section-standards"]
      standard:
        tags: ["dpgn-section-standard"]
        introduction:
          tags: ["dpgn-section-intro-standard"]
        relatedguidelines:
          title:
            en: "Related guidelines"
            fr: "Lignes directrices connexes"
          tags: ["dpgn-section-guidelines-related"]
        guidelines:
          title:
            en: "Guidelines"
            fr: "Lignes directrices"
          tags: ["dpgn-section-guidelines"]
          guideline:
            tags: ["dpgn-section-guideline"]
            introduction:
               tags: ["dpgn-section-intro-guideline"]
            checklist:
              title:
                en: "Checklist"
                fr: "Liste de contrôle"
              tags: ["dpgn-section-checklist"]
            guides:
              title:
                en: "Implementation guides"
                fr: "Guides d’application"
              tags: ["dpgn-section-guides"]
            solutions:
              title:
                en: "Reusable solutions"
                fr: "Solutions réutilisables"
              tags: ["dpgn-section-solutions"]
            similar:
              title:
                en: "Similar resources"
                fr: "Ressources similaires"
              tags: ["dpgn-section-similar"]

# Playbook section translations
ComparisonPlaybookIntro:
  en: Comparison of the Digital Playbook to similar resources
  fr: Comparaison du guide numérique à des ressources similaires
ComparisonPlaybookTitle:
  en: Government of Canada Digital Playbook comparison table
  fr: Tableau comparatif du guide numérique du gouvernement du Canada
ComparisonPlaybookFile:
  en: gc-digital-playbook-comparison-table
  fr: tableau-comparatif-guide-numerique-gc
Colon:
  en: ":"
  fr: " :"

# Canada.ca theme translations
home:
  en: Home
  fr: Accueil
language:
  en: English
  fr: Français
SkipToMain:
  en: Skip to main content
  fr: Passer au contenu principal
SkipToAbout:
  en: Skip to "About this site"
  fr: Passer à «&#160;À propos de ce site&#160;»
LanguageSelection:
  en: Language selection
  fr: Sélection de la langue
GoC:
  en: Government of Canada
  fr: Gouvernement du Canada
SearchAndMenus:
  en: Search and menus
  fr: Recherche et menus
SearchWebsite:
  en: Search website
  fr: Recherchez le site Web
SearchCanadaCa:
  en: Search Canada.ca
  fr: Rechercher dans Canada.ca
Search:
  en: Search
  fr: Recherche
TopicsMenu:
  en: Topics menu
  fr: Menu des sujets
YouAreHere:
  en: You are here
  fr: Vous êtes ici
GCActivitiesInitiatives:
  en: Government of Canada activities and initiatives
  fr: Activités et initiatives du gouvernement du Canada
TopicsMenu1:
  en: Jobs
  fr: Emplois
TopicsMenu1URL:
  en: https://www.canada.ca/en/services/jobs.html
  fr: https://www.canada.ca/fr/services/emplois.html
TopicsMenu2:
  en: Immigration
  fr: Immigration
TopicsMenu2URL:
  en: https://www.canada.ca/en/services/immigration-citizenship.html
  fr: https://www.canada.ca/fr/services/immigration-citoyennete.html
TopicsMenu3:
  en: Travel
  fr: Voyage
TopicsMenu3URL:
  en: https://travel.gc.ca
  fr: http://voyage.gc.ca/
TopicsMenu4:
  en: Business
  fr: Entreprises
TopicsMenu4URL:
  en: https://www.canada.ca/en/services/business.html
  fr: https://www.canada.ca/fr/services/entreprises.html
TopicsMenu5:
  en: Benefits
  fr: Prestations
TopicsMenu5URL:
  en: https://www.canada.ca/en/services/benefits.html
  fr: https://www.canada.ca/fr/services/prestations.html
TopicsMenu6:
  en: Health
  fr: Santé
TopicsMenu6URL:
  en: https://www.canada.ca/en/services/health.html
  fr: https://www.canada.ca/fr/services/sante.html
TopicsMenu7:
  en: Taxes
  fr: Impôts
TopicsMenu7URL:
  en: https://www.canada.ca/en/services/taxes.html
  fr: https://www.canada.ca/fr/services/impots.html
TopicsMenu8:
  en: More services
  fr: Autres services
TopicsMenu8URL:
  en: https://www.canada.ca/en/services.html
  fr: https://www.canada.ca/fr/services.html
FooterSection1:
  en: About government
  fr: Au sujet du gouvernement
FooterSection1Item1:
  en: Contact us
  fr: Contactez-nous
FooterSection1Item1URL:
  en: https://www.canada.ca/en/contact.html
  fr: https://www.canada.ca/fr/contact.html
FooterSection1Item2:
  en: Departments and agencies
  fr: Ministères et organismes
FooterSection1Item2URL:
  en: https://www.canada.ca/en/government/dept.html
  fr: https://www.canada.ca/fr/gouvernement/min.html
FooterSection1Item3:
  en: Public service and military
  fr: Fonction publique et force militaire
FooterSection1Item3URL:
  en: https://www.canada.ca/en/government/publicservice.html
  fr: https://www.canada.ca/fr/gouvernement/fonctionpublique.html
FooterSection1Item4:
  en: News
  fr: Nouvelles
FooterSection1Item4URL:
  en: https://www.canada.ca/en/news.html
  fr: https://www.canada.ca/fr/nouvelles.html
FooterSection1Item5:
  en: Treaties, laws and regulations
  fr: Traités, lois et règlements
FooterSection1Item5URL:
  en: https://www.canada.ca/en/government/system/laws.html
  fr: https://www.canada.ca/fr/gouvernement/systeme/lois.html
FooterSection1Item6:
  en: Government-wide reporting
  fr: Rapports à l&#39;échelle du gouvernement
FooterSection1Item6URL:
  en: https://www.canada.ca/en/transparency/reporting.html
  fr: https://www.canada.ca/fr/transparence/rapports.html
FooterSection1Item7:
  en: Prime Minister
  fr: Premier ministre
FooterSection1Item7URL:
  en: http://pm.gc.ca/eng
  fr: http://pm.gc.ca/fra
FooterSection1Item8:
  en: How government works
  fr: Comment le gouvernement fonctionne
FooterSection1Item8URL:
  en: https://www.canada.ca/en/government/system.html
  fr: https://www.canada.ca/fr/gouvernement/systeme.html
FooterSection1Item9:
  en: Open government
  fr: Gouvernement ouvert
FooterSection1Item9URL:
  en: http://open.canada.ca/en/
  fr: http://ouvert.canada.ca/
FooterSection2:
  en: About this site
  fr: À propos de ce site
FooterSection2Item1:
  en: Social media
  fr: Médias sociaux
FooterSection2Item1URL:
  en: https://www.canada.ca/en/social.html
  fr: https://www.canada.ca/fr/sociaux.html
FooterSection2Item2:
  en: Mobile applications
  fr: Applications mobiles
FooterSection2Item2URL:
  en: https://www.canada.ca/en/mobile.html
  fr: https://www.canada.ca/fr/mobile.html
FooterSection2Item3:
  en: About Canada.ca
  fr: À propos de Canada.ca
FooterSection2Item3URL:
  en: https://www1.canada.ca/en/newsite.html
  fr: https://www.canada.ca/fr/gouvernement/a-propos.html
FooterSection2Item4:
  en: Terms and conditions
  fr: Avis
FooterSection2Item4URL:
  en: https://www.canada.ca/en/transparency/terms.html
  fr: https://www.canada.ca/fr/transparence/avis.html
FooterSection2Item5:
  en: Privacy
  fr: Confidentialité
FooterSection2Item5URL:
  en: https://www.canada.ca/en/transparency/privacy.html
  fr: https://www.canada.ca/fr/transparence/confidentialite.html
TopOfPage:
  en: Top of Page
  fr: Haut de la page
GCWordmark:
  en: Symbol of the Government of Canada
  fr: Symbole du gouvernement du Canada

# Filter strings
DefaultTag: "dpgn-tags" # Output as a class for any element that has a tag array (empty or not)
Filters:
  en: Filters
  fr: Filtres
ShowFilters:
  en: Show filters
  fr: Afficher les filtres
DevelopmentStage:
  en: Development stage
  fr: Stage de développement
Alpha:
  en: Alpha
  fr: Alpha
Beta:
  en: Beta
  fr: Bêta
Live:
  en: Live
  fr: En direct
SectionType:
  en: Section type
  fr: Type de section
ForAStandard:
  en: for a standard
  fr: pour une norme
List:
  en: list
  fr: liste
Introduction:
  en: Introduction
  fr: Introduction
Guideline:
  en: Guideline
  fr: Ligne directrice
ForAGuideline:
  en: for a guideline
  fr: pour une ligne directrice
ApplyFilters:
  en: Apply filters
  fr: Appliquer les filtres
RememberFilters:
  en: Remember my filters next time
  fr: Rappeler les filtres la prochaine fois
ExclusiveFilters:
  en: Exclusive filters
  fr: Filtres exclusifs
DigitalArchitectural:
  en: Build It Right - OneGC Architectural Checklist (draft)
  fr: Construisez-le bien - Liste de contrôle architecturale unGC (ébauche)

# Feedback and view source translations
PageColon:
  en: "Page:"
  fr: "Page :"
FeedbackAsk:
  en: Give feedback about this page
  fr: Donnez votre avis sur cette page
ViewSourceGitHub:
  en: View source on GitHub
  fr: Voir la source sur GitHub
SubmitIssueGitHub:
  en: Submit an issue on GitHub
  fr: Soumettre un problème sur GitHub
CurrentIssuesGitHub:
  en: view current issues on GitHub
  fr: voir les problèmes actuels sur GitHub
GCcollabComment:
  en: Submit a comment in the OneGC GCcollab group
  fr: Soumettre un commentaire dans le groupe unGC à GCcollab
FeedbackIntro:
  en: "We encourage you to submit feedback using one of the following open feedback options:"
  fr: "Nous vous encourageons à soumettre vos commentaires en utilisant l'une des options de commentaires ouvertes suivantes&#160;:"
FeedbackEmailIntro:
  en: If you encounter issues with the open feedback options then please contact us through the
  fr: Si vous rencontrez des problèmes avec les options de commentaires ouverte, veuillez nous contacter via le
FeedbackEmailLink:
  en: OneGC email account
  fr: compte de messagerie unGC

# Pagination translations
Previous:
  en: Previous
  fr: Précédent
Next:
  en: Next
  fr: Suivant
GoTo:
  en: Go to
  fr: Aller à la

# Comparison table translations
DigitalStandardNbsp:
  en: Digital&#160;standard
  fr: Norme&#160;numérique
DigitalPlaybookGuideline:
  en: Digital Playbook guideline
  fr: Ligne directrice du guide numérique
ComparableStandardsCriteria:
  en: Comparable standards / criteria
  fr: Normes / critères comparables

# View template strings
RelatedTo:
  en: related to
  fr: relié à
